name: boost_sys_weblurk
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.2

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  google_fonts: ^6.2.1
  validatorless: ^1.2.3
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  ###
  go_router: ^14.6.2
  asuka: ^2.2.1
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  flutter_secure_storage: ^9.2.4
  universal_platform: ^1.1.0
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  process_run: ^1.2.4
  flutter_volume_controller: ^1.3.3
  window_manager: ^0.4.3
  shorebird_code_push: ^1.1.6
  ffi: ^2.1.3
  win32: ^5.8.0
  provider: ^6.1.2
  desktop_webview_window: ^0.2.3
  web_socket_channel: ^3.0.2
  mockito: ^5.4.5
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1
  modular_test: ^2.0.0
  # firebase_core: ^3.3.0
  # firebase_remote_config: ^5.0.4
  # firebase_analytics: ^11.2.1
  # firebase_messaging: ^15.0.4
  webview_windows: ^0.4.0
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  
  flutter_lints: ^5.0.0

flutter:  
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo-cla-boost.png
    - .env
    - shorebird.yaml