name: boost_sys_weblurk
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.13+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  ###
  asuka: ^2.2.1

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  # flutter_inappwebview: ^6.1.5
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  mockito: ^5.4.5
  mocktail: ^1.0.4
  network_image_mock: ^2.1.1
  process_run: ^1.2.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  shorebird_code_push: ^2.0.4
  universal_platform: ^1.1.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  validatorless: ^1.2.3
  web_socket_channel: ^3.0.2
  webview_flutter: ^4.7.0
  
  webview_windows: ^0.4.0
  win32: ^5.8.0
  # flutter_volume_controller: ^1.3.3  # Removido - agora controla apenas o áudio do app
  window_manager: ^0.4.3

dev_dependencies:
  build_runner: ^2.1.8

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo-cla-boost.png
    - .env
    - shorebird.yaml
