name: Build Flutter Windows App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.24.3'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows --release

    - name: Increment Version
      run: |
        if [ -f "version.sh" ]; then
          bash version.sh
        else
          echo "NEW_TAG=v1.0.0" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Boost-SysWebLurk-${{ env.NEW_TAG || 'latest' }}
        path: build/windows/runner/Release/