name: Build Flutter Windows App

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows --release

    - name: Increment Version
      run: bash version.sh
      id: version

    - name: Create Release ZIP
      run: |
        cd build\windows\x64\runner\Release
        7z a -tzip ../../../../../Boost-SysWebLurk-${{ env.NEW_TAG }}.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Boost-SysWebLurk-${{ env.NEW_TAG }}
        path: build/windows/runner/Release/
        retention-days: 90

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: Boost-SysWebLurk-${{ env.NEW_TAG }}.zip
        tag_name: ${{ env.NEW_TAG }}
        name: Boost-SysWebLurk v${{ env.NEW_TAG }}
        draft: false
        prerelease: false
        body: |
          Release automático da versão ${{ env.NEW_TAG }}
          
          ### Mudanças nesta versão
          - Mudanças no salvamento do score
          - Correção do pooling de troca de canais
          
          ### Screenshots
          ![Screenshot 1](https://raw.githubusercontent.com/barba2k2/boost_sys_weblurk/master/assets/screenshots/img1.png)
          ![Screenshot 2](https://raw.githubusercontent.com/barba2k2/boost_sys_weblurk/master/assets/screenshots/img2.png)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}