name: Build Flutter Windows App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows
      run: flutter build windows --release

    # Rodar o script para determinar a próxima versão
    - name: Increment Version
      run: bash version.sh

    # Usar a nova versão para nomear o artefato
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Boost-SysWebLurk-${{ env.NEW_TAG }}
        path: build/windows/runner/Release/