name: Diagnostic Check

on:
  push:
    branches: ["1.0.14+1"]
  workflow_dispatch:

jobs:
  diagnostic:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check GitHub Context
        shell: powershell
        run: |
          Write-Output "GitHub Event: ${{ github.event_name }}"
          Write-Output "Branch: ${{ github.ref_name }}"
          Write-Output "SHA: ${{ github.sha }}"
          Write-Output "Actor: ${{ github.actor }}"
          Write-Output "Repository: ${{ github.repository }}"
          Write-Output "Workflow: ${{ github.workflow }}"
          Write-Output "Run ID: ${{ github.run_id }}"

      - name: Check Secrets
        shell: powershell
        run: |
          if ("${{ secrets.SHOREBIRD_TOKEN }}" -ne "") {
            Write-Output "OK: SHOREBIRD_TOKEN esta configurado"
          } else {
            Write-Output "ERROR: SHOREBIRD_TOKEN nao esta configurado"
          }

          if ("${{ secrets.GITHUB_TOKEN }}" -ne "") {
            Write-Output "OK: GITHUB_TOKEN esta configurado"
          } else {
            Write-Output "ERROR: GITHUB_TOKEN nao esta configurado"
          }

      - name: Check Workflow Files
        shell: powershell
        run: |
          Write-Output "Workflow files:"
          Get-ChildItem .github/workflows/

          Write-Output "Content of simple-test.yml:"
          Get-Content .github/workflows/simple-test.yml

      - name: Check Git Status
        shell: powershell
        run: |
          Write-Output "Git status:"
          git status
          Write-Output "Last commits:"
          git log --oneline -5
