name: Manual Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Tipo de teste"
        required: true
        default: "basic"
        type: choice
        options:
          - basic
          - full

jobs:
  manual-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Basic Test
        if: inputs.test_type == 'basic'
        shell: powershell
        run: |
          Write-Output "OK: Teste basico executado com sucesso!"
          Write-Output "Branch: ${{ github.ref_name }}"
          Write-Output "Event: ${{ github.event_name }}"

      - name: Full Test
        if: inputs.test_type == 'full'
        shell: powershell
        run: |
          Write-Output "Teste completo iniciado..."
          Write-Output "Branch: ${{ github.ref_name }}"
          Write-Output "Event: ${{ github.event_name }}"
          Write-Output "SHA: ${{ github.sha }}"
          Write-Output "Actor: ${{ github.actor }}"

          Write-Output "Verificando arquivos de workflow:"
          Get-ChildItem .github/workflows/

          Write-Output "Ultimos commits:"
          git log --oneline -5

          if ("${{ secrets.SHOREBIRD_TOKEN }}" -ne "") {
            Write-Output "OK: SHOREBIRD_TOKEN configurado"
          } else {
            Write-Output "ERROR: SHOREBIRD_TOKEN nao configurado"
          }
